# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20180615_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='title'),
        ),
    ]
